server:
  error:
    include-message: always
logging:
  level:
    root: INFO
    com.viktorkuts: DEBUG
    org.hibernate.sql: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

---

spring:
  config:
    activate:
      on-profile: h2
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:eventplanner-db;DB_CLOSE_DELAY=-1;NON_KEYWORDS=YEAR
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        auto-quote-keyword: true

---

spring:
  datasource:
    hikari:
      initialization-fail-timeout: 60000
    url: jdbc:mysql://mysql1/eventplanner-db
    username: user
    password: pwd

  jpa:
    hibernate:
      ddl-auto: none
  config:
    activate:
      on-profile: docker

  sql:
    init:
      platform: mysql
      mode: always
server:
  port: 8080